project_id = "wvmfzlogijvqcsgablrb"

[auth.external.hibp]
enabled = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.sync-qogita-to-gist]
verify_jwt = false

[functions.sync-gist-to-db]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-and-signup]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.reset-badge]
verify_jwt = false

[functions.sync-eany-gist-to-db]
verify_jwt = false

[functions.sync-stripe-payments]
verify_jwt = false

[functions.send-payment-failed-email]
verify_jwt = false

[functions.affiliate-signup]
verify_jwt = false

[functions.affiliate-verify-code]
verify_jwt = false

[functions.affiliate-login]
verify_jwt = false

[functions.affiliate-resend-code]
verify_jwt = false

[functions.affiliate-track-click]
verify_jwt = false

[functions.airtable-contacts]
verify_jwt = false

[functions.airtable-users]
verify_jwt = false

[functions.sync-user-to-airtable]
verify_jwt = false

[functions.sync-all-users-to-airtable]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.verify-suite-payment]
verify_jwt = false

[functions.create-suite-checkout]
verify_jwt = false

[functions.systeme-io-webhook]
verify_jwt = false

[functions.admin-impersonation]
verify_jwt = false

[functions.sync-qogita-catalogue]
verify_jwt = false

[functions.sync-qogita-from-sheets]
verify_jwt = false

[functions.sync-eany-from-sheets]
verify_jwt = false

[functions.sync-vibraforce-catalogue]
verify_jwt = false

[functions.sync-eany-catalogue]
verify_jwt = false

[functions.sync-product-find-from-sheets]
verify_jwt = false

[functions.sync-discord-product-find]
verify_jwt = false

[functions.admin-get-subscriptions]
verify_jwt = false
