project_id = "wvmfzlogijvqcsgablrb"

[auth.external.hibp]
enabled = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.sync-qogita-to-gist]
verify_jwt = false

[functions.sync-gist-to-db]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-and-signup]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.reset-badge]
verify_jwt = false

[functions.sync-eany-gist-to-db]
verify_jwt = false

[functions.sync-stripe-payments]
verify_jwt = false

[functions.send-payment-failed-email]
verify_jwt = false

[functions.affiliate-signup]
verify_jwt = false

[functions.affiliate-verify-code]
verify_jwt = false

[functions.affiliate-login]
verify_jwt = false

[functions.affiliate-resend-code]
verify_jwt = false

[functions.affiliate-track-click]
verify_jwt = false

[functions.airtable-contacts]
verify_jwt = false

[functions.airtable-users]
verify_jwt = false
